### ISSUE TITLE
Cloud Extension respond 400 to "PROMO_CODE" offer types

### ISSUE THREAD

**Issue by ThomasEcalle** [Purchasely/Purchasely-Firebase-Extension#74]
Hi !

First of all, thank you for this extension which saves us some time when developing with Firebase :)

I work with it with one of my customer, but I am facing a weird issue.
To begin with, here are some basic information about my setup:
```
cloud function version: 1.0.6
my endpoint url: https://europe-west3-teasyapp-fb516.cloudfunctions.net/ext-purchasely-in-app-purchases-purchaselyWebhookHandler
```

The issue:

A lot of our users are having some troubles to apply promotional code (either on Android or iOS).
When I check on the Purchasely console, it seems that the cloud function is responding with a 400 error code with that kind of payload:

```
{
  "message": "400 Bad Request",
  "headers": {
    "date": "Mon, 13 Mar 2023 14:03:31 GMT",
    "etag": "W/\"ff-C2YDMxArNBZoSIkJAfRmmynEDuc\"",
    "server": "Google Frontend",
    "alt_svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
    "content_type": "application/json; charset=utf-8",
    "content_length": "255",
    "function_execution_id": "ifdkllmwwmf0",
    "x_cloud_trace_context": "6a0b895db39fbd00d4fd06d8bc3398cb;o=1"
  },
  "body": {
    "errors": [
      {
        "params": {
          "allowedValues": [
            "INTRO_OFFER",
            "FREE_TRIAL",
            "PROMOTIONAL_OFFER",
            "OFFER_CODE",
            "NONE"
          ]
        },
        "keyword": "enum",
        "message": "must be equal to one of the allowed values",
        "schemaPath": "#/properties/offer_type/enum",
        "instancePath": "/offer_type"
      }
    ]
  }
}
```

But here is the kind of payload sent by the Purchasely console:

```
{
  "plan": "monthly_0daystrial",
  "store": "APPLE_APP_STORE",
  "product": "20230105",
  "user_id": "JoPi9iV0WzZ5q8qFIf0T4tXoZYp1",
  "event_id": "4f77681f-29dc-46a6-b6ef-2ab95a697583",
  "placement": "placement-2",
  "event_name": "ACTIVATE",
  "offer_type": "PROMO_CODE",
  "api_version": 3,
  "device_type": "PHONE",
  "environment": "PRODUCTION",
  "presentation": "paywall-2-C-yearly-6999monthly-999",
  "purchased_at": "2023-03-10T17:58:26.000Z",
  "purchase_type": "RENEWING_SUBSCRIPTION",
  "store_country": "FR",
  "next_renewal_at": "2023-04-10T16:58:26.000Z",
  "purchased_at_ms": 1678471106000,
  "event_created_at": "2023-03-10T17:58:53.965Z",
  "is_family_shared": false,
  "offer_identifier": "MELBAPREMIUM",
  "store_product_id": "LIVE_apple_sub_monthly_0daystrial_9.99",
  "customer_currency": "EUR",
  "plan_price_in_eur": 0.0,
  "next_renewal_at_ms": 1681145906000,
  "event_created_at_ms": 1678471133965,
  "offer_code_ref_name": "MELBAPREMIUM",
  "store_app_bundle_id": "ai.teasy.client",
  "subscription_status": "AUTO_RENEWING",
  "promotional_offer_id": "5a339cc4-fc03-4b42-837b-bd968472dabb",
  "store_transaction_id": "160001483542521",
  "original_purchased_at": "2023-03-10T17:58:27.000Z",
  "original_purchased_at_ms": 1678471107000,
  "cumulated_revenues_in_eur": null,
  "effective_next_renewal_at": "2023-04-10T16:58:26.000Z",
  "purchasely_subscription_id": "subs_J0CucazZjNbMCZ38jRQiGXLTGOriHE",
  "effective_next_renewal_at_ms": 1681145906000,
  "store_original_transaction_id": "160001483542521",
  "plan_price_in_customer_currency": 0.0
}
```

So... it seems that you are sending an offer type of `PROMO_CODE` but that the cloud extension does not know this type.

Is it a regression of the cloud function ? Because it worked before.

I believe that you could understand it is a big issue for us as our customers can't properly use their promotional codes and I'll be very happy if you could explain the reason and the fixes to apply. 

Thank you in advance and have a great day

**Comment by ste26054** [comment]
Hi @ThomasEcalle, thanks for pointing this issue, we are working on a fix and will deploy it asap!

**Comment by ThomasEcalle** [comment]
Hi @ste26054 

Thanks for the quick answer !
Please do not hesitate if you need more info, good luck for the fix !

**Comment by ste26054** [comment]
Hey @ThomasEcalle, we have just released version `1.0.7` of the extension, that should fix the issue!

**Comment by ste26054** [comment]
@ThomasEcalle if you can confirm to me when the update to `1.0.7` is done, so I can manually retrigger all webhooks that failed due to the error in previous version (I have the list of users impacted at hand)

We have an exponential retry strategy by default when webhook attempts fail, so it may take longer to recover for webhooks that already had lots of attempts.

**Comment by ThomasEcalle** [comment]
@ste26054  I can confirm that I have updated the cloud function to 1.0.7

Oh ok I understand, very nice if you can re-trigger them manually indeed, thank you ! :)

<img width="1019" alt="Capture d’écran 2023-03-14 à 15 36 29" src="https://user-images.githubusercontent.com/15629864/225035258-92ef7c8f-5f8d-4fe7-b4a2-d8cb69c42e02.png">

**Comment by ste26054** [comment]
@ThomasEcalle I can confirm that all pending webhooks went through 🙂

**Comment by ThomasEcalle** [comment]
Awesome @ste26054  !!

Thanks a lot for your help on this subject, you had a great reactivity and I am thankfull for that.

You can close the issue, have a good day :)

**Comment by ste26054** [comment]
No problem, thanks for pointing out the issue!
