### ISSUE TITLE
[FLUTTER] purchasely_flutter not working since 1.5.0

### ISSUE THREAD

**Issue by ThomasEcalle** [Purchasely/Purchasely-Firebase-Extension#79]
Hi !

Sorry, me gain 😅

I would like to report a bug on the Purchasely Flutter SDK and I am sorry to write it here, as I know this issue is not directly related to the Purchasely Cloud Function, but I found nowhere to report bugs as the Flutter SDK does not have a public repository.

What is the right way to report SDKs bugs to Purchasely ?
I found the email address "hello@purchasely.com" on your GitHub organization but... I believe people behind this address are not technical people.

If there is a clear process, please feel free to tell me and I would erase my comment here to post it in the appropriate area :)

**The issue:**

As a Flutter devleoper, I am using the [purchasely_flutter](https://pub.dev/packages/purchasely_flutter) SDK to handle in_app for one of my clients.

I previously was on the `1.4.2` version and everything was working quite well.

My client would like to use the new Purchasely feature `Use your own paywall` which, [regarding the official documentation](https://docs.purchasely.com/advanced-features/use-your-own-paywall), needs the `purchasely_flutter` to be above `1.5.0`.

Actually, the package seems to be on version `1.6.2`.

But **none of the versions after `1.5.0` seem to works anymore.**

I get this exception during package initialization each time:

```
[log] [error] Error initializing purchasely: PlatformException(0, Your dependency for GOOGLE_PLAY_STORE is not up to date, your current version is 34200, please update to version 3.5.0, InvalidStoreVersion{
message : Your dependency for GOOGLE_PLAY_STORE is not up to date, your current version is 34200, please update to version 3.5.0
}
	at io.purchasely.managers.PLYStoreManager.checkAvailabilityOfInAppPurchase$core_3_5_0_release(PLYStoreManager.kt:286)
	at io.purchasely.managers.PLYManager.init$core_3_5_0_release(PLYManager.kt:96)
	at io.purchasely.managers.PLYManager$configure$2$1.invokeSuspend(PLYManager.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
, null) 
```

It seems that there is an issue with the `GOOGLE_PLAY_STORE` version but I believe it is a dependency of the package itself, not something to handle on the app developer part, right ?

Anyway nothing changed in the documentation about the package setup so i believe it is a bug but feel free to tell me if I am wrong and if, maybe, the documentation is juste outdated.

Once again, sorry for diturbing your day, as I know this is not the good repository 😕

Thank you in advance for your help 🙏

**Comment by ste26054** [comment]
Hi again Thomas, if you have access to our console you should be able to reach us from there through intercom, where it would have all the context related to your app, etc.
I am forwarding your issue to the team!

**Comment by kherembourg** [comment]
Hello @ThomasEcalle 

This error means you did not do one of these 2 things :
- Old way: Update the build.gradle file to upgrade the `purchasely:google-play` dependency to version 3.5.0
- Recommended: Update the flutter dependency `purchasely_google` to version 1.6.2 like `purchasely_flutter`. 
Please refer to https://docs.purchasely.com/quick-start-1/sdk-installation/flutter-sdk#google-play-billing

`purchasely_flutter` contains purchasley core SDK but does not include what is necessary for Google, you need to add `purchasley_google` for that and both have to use the same version

Feel free to contact support@purchasely.com for any questions or issues

**Comment by ThomasEcalle** [comment]
Hi @kherembourg 

Thanks a lot for your answer ! 
I think there is a little missunderstanding in the documentation as `purchasely_google` was **not mandatory** for previous versions but, as I see, is now.

I have never added `purchasely_google` before, when I was on `purchasely_flutter` version `1.4.2`.... and everything was working fine. Is it normal ?

That is quite a breaking change that should maybe be better higlighted in documentation.
Today the doc says "To add Google as a store, you **can** use our plugin" which could maybe be missleading and understood as something **not required**, what do you think ?

But thanks for your response, I will do that and I will definitly report to [support@purchasely.com](mailto:support@purchasely.com) next time, sorry for posting in the wrong repository.
